/**
 * Static data for the 68 teams in the 2025 NCAA Tournament.
 * Sourced from ESPN scoreboard API.
 * This file has no side effects — safe to import from any script.
 */

export interface TeamSeed {
  name: string;
  shortName: string;
  abbreviation: string;
  espnId: string;
  seed: number;
  region: "south" | "east" | "west" | "midwest";
}

export const TOURNAMENT_2025_TEAMS: TeamSeed[] = [
  // SOUTH REGION (18 teams — includes 2 First Four pairs at seeds 11 and 16)
  {
    name: "Auburn Tigers",
    shortName: "Auburn",
    abbreviation: "AUB",
    espnId: "2",
    seed: 1,
    region: "south",
  },
  {
    name: "Michigan State Spartans",
    shortName: "Michigan St",
    abbreviation: "MSU",
    espnId: "127",
    seed: 2,
    region: "south",
  },
  {
    name: "Iowa State Cyclones",
    shortName: "Iowa State",
    abbreviation: "ISU",
    espnId: "66",
    seed: 3,
    region: "south",
  },
  {
    name: "Texas A&M Aggies",
    shortName: "Texas A&M",
    abbreviation: "TA&M",
    espnId: "245",
    seed: 4,
    region: "south",
  },
  {
    name: "Michigan Wolverines",
    shortName: "Michigan",
    abbreviation: "MICH",
    espnId: "130",
    seed: 5,
    region: "south",
  },
  {
    name: "Ole Miss Rebels",
    shortName: "Ole Miss",
    abbreviation: "MISS",
    espnId: "145",
    seed: 6,
    region: "south",
  },
  {
    name: "Marquette Golden Eagles",
    shortName: "Marquette",
    abbreviation: "MARQ",
    espnId: "269",
    seed: 7,
    region: "south",
  },
  {
    name: "Louisville Cardinals",
    shortName: "Louisville",
    abbreviation: "LOU",
    espnId: "97",
    seed: 8,
    region: "south",
  },
  {
    name: "Creighton Bluejays",
    shortName: "Creighton",
    abbreviation: "CREI",
    espnId: "156",
    seed: 9,
    region: "south",
  },
  {
    name: "New Mexico Lobos",
    shortName: "New Mexico",
    abbreviation: "UNM",
    espnId: "167",
    seed: 10,
    region: "south",
  },
  {
    name: "North Carolina Tar Heels",
    shortName: "North Carolina",
    abbreviation: "UNC",
    espnId: "153",
    seed: 11,
    region: "south",
  },
  {
    name: "San Diego State Aztecs",
    shortName: "San Diego St",
    abbreviation: "SDSU",
    espnId: "21",
    seed: 11,
    region: "south",
  },
  {
    name: "UC San Diego Tritons",
    shortName: "UC San Diego",
    abbreviation: "UCSD",
    espnId: "28",
    seed: 12,
    region: "south",
  },
  {
    name: "Yale Bulldogs",
    shortName: "Yale",
    abbreviation: "YALE",
    espnId: "43",
    seed: 13,
    region: "south",
  },
  {
    name: "Lipscomb Bisons",
    shortName: "Lipscomb",
    abbreviation: "LIP",
    espnId: "288",
    seed: 14,
    region: "south",
  },
  {
    name: "Bryant Bulldogs",
    shortName: "Bryant",
    abbreviation: "BRY",
    espnId: "2803",
    seed: 15,
    region: "south",
  },
  {
    name: "Alabama State Hornets",
    shortName: "Alabama St",
    abbreviation: "ALST",
    espnId: "2011",
    seed: 16,
    region: "south",
  },
  {
    name: "Saint Francis Red Flash",
    shortName: "Saint Francis",
    abbreviation: "SFPA",
    espnId: "2598",
    seed: 16,
    region: "south",
  },

  // EAST REGION (17 teams — includes 1 First Four pair at seed 16)
  {
    name: "Duke Blue Devils",
    shortName: "Duke",
    abbreviation: "DUKE",
    espnId: "150",
    seed: 1,
    region: "east",
  },
  {
    name: "Alabama Crimson Tide",
    shortName: "Alabama",
    abbreviation: "ALA",
    espnId: "333",
    seed: 2,
    region: "east",
  },
  {
    name: "Wisconsin Badgers",
    shortName: "Wisconsin",
    abbreviation: "WIS",
    espnId: "275",
    seed: 3,
    region: "east",
  },
  {
    name: "Arizona Wildcats",
    shortName: "Arizona",
    abbreviation: "ARIZ",
    espnId: "12",
    seed: 4,
    region: "east",
  },
  {
    name: "Oregon Ducks",
    shortName: "Oregon",
    abbreviation: "ORE",
    espnId: "2483",
    seed: 5,
    region: "east",
  },
  {
    name: "BYU Cougars",
    shortName: "BYU",
    abbreviation: "BYU",
    espnId: "252",
    seed: 6,
    region: "east",
  },
  {
    name: "Saint Mary's Gaels",
    shortName: "Saint Mary's",
    abbreviation: "SMC",
    espnId: "2608",
    seed: 7,
    region: "east",
  },
  {
    name: "Mississippi State Bulldogs",
    shortName: "Mississippi St",
    abbreviation: "MSST",
    espnId: "344",
    seed: 8,
    region: "east",
  },
  {
    name: "Baylor Bears",
    shortName: "Baylor",
    abbreviation: "BAY",
    espnId: "239",
    seed: 9,
    region: "east",
  },
  {
    name: "Vanderbilt Commodores",
    shortName: "Vanderbilt",
    abbreviation: "VAN",
    espnId: "238",
    seed: 10,
    region: "east",
  },
  {
    name: "VCU Rams",
    shortName: "VCU",
    abbreviation: "VCU",
    espnId: "2670",
    seed: 11,
    region: "east",
  },
  {
    name: "Liberty Flames",
    shortName: "Liberty",
    abbreviation: "LIB",
    espnId: "2335",
    seed: 12,
    region: "east",
  },
  {
    name: "Akron Zips",
    shortName: "Akron",
    abbreviation: "AKR",
    espnId: "2006",
    seed: 13,
    region: "east",
  },
  {
    name: "Montana Grizzlies",
    shortName: "Montana",
    abbreviation: "MONT",
    espnId: "149",
    seed: 14,
    region: "east",
  },
  {
    name: "Robert Morris Colonials",
    shortName: "Robert Morris",
    abbreviation: "RMU",
    espnId: "2523",
    seed: 15,
    region: "east",
  },
  {
    name: "Mount St. Mary's Mountaineers",
    shortName: "Mount St Marys",
    abbreviation: "MSM",
    espnId: "116",
    seed: 16,
    region: "east",
  },
  {
    name: "American University Eagles",
    shortName: "American",
    abbreviation: "AMER",
    espnId: "44",
    seed: 16,
    region: "east",
  },

  // WEST REGION (16 teams — no First Four games)
  {
    name: "Florida Gators",
    shortName: "Florida",
    abbreviation: "FLA",
    espnId: "57",
    seed: 1,
    region: "west",
  },
  {
    name: "St. John's Red Storm",
    shortName: "St John's",
    abbreviation: "SJU",
    espnId: "2599",
    seed: 2,
    region: "west",
  },
  {
    name: "Texas Tech Red Raiders",
    shortName: "Texas Tech",
    abbreviation: "TTU",
    espnId: "2641",
    seed: 3,
    region: "west",
  },
  {
    name: "Maryland Terrapins",
    shortName: "Maryland",
    abbreviation: "MD",
    espnId: "120",
    seed: 4,
    region: "west",
  },
  {
    name: "Memphis Tigers",
    shortName: "Memphis",
    abbreviation: "MEM",
    espnId: "235",
    seed: 5,
    region: "west",
  },
  {
    name: "Missouri Tigers",
    shortName: "Missouri",
    abbreviation: "MIZ",
    espnId: "142",
    seed: 6,
    region: "west",
  },
  {
    name: "Kansas Jayhawks",
    shortName: "Kansas",
    abbreviation: "KU",
    espnId: "2305",
    seed: 7,
    region: "west",
  },
  {
    name: "UConn Huskies",
    shortName: "UConn",
    abbreviation: "CONN",
    espnId: "41",
    seed: 8,
    region: "west",
  },
  {
    name: "Oklahoma Sooners",
    shortName: "Oklahoma",
    abbreviation: "OU",
    espnId: "201",
    seed: 9,
    region: "west",
  },
  {
    name: "Arkansas Razorbacks",
    shortName: "Arkansas",
    abbreviation: "ARK",
    espnId: "8",
    seed: 10,
    region: "west",
  },
  {
    name: "Drake Bulldogs",
    shortName: "Drake",
    abbreviation: "DRKE",
    espnId: "2181",
    seed: 11,
    region: "west",
  },
  {
    name: "Colorado State Rams",
    shortName: "Colorado St",
    abbreviation: "CSU",
    espnId: "36",
    seed: 12,
    region: "west",
  },
  {
    name: "Grand Canyon Lopes",
    shortName: "Grand Canyon",
    abbreviation: "GCU",
    espnId: "2253",
    seed: 13,
    region: "west",
  },
  {
    name: "UNC Wilmington Seahawks",
    shortName: "UNC Wilmington",
    abbreviation: "UNCW",
    espnId: "350",
    seed: 14,
    region: "west",
  },
  {
    name: "Omaha Mavericks",
    shortName: "Omaha",
    abbreviation: "OMA",
    espnId: "2437",
    seed: 15,
    region: "west",
  },
  {
    name: "Norfolk State Spartans",
    shortName: "Norfolk St",
    abbreviation: "NORF",
    espnId: "2450",
    seed: 16,
    region: "west",
  },

  // MIDWEST REGION (17 teams — includes 1 First Four pair at seed 11)
  {
    name: "Houston Cougars",
    shortName: "Houston",
    abbreviation: "HOU",
    espnId: "248",
    seed: 1,
    region: "midwest",
  },
  {
    name: "Tennessee Volunteers",
    shortName: "Tennessee",
    abbreviation: "TENN",
    espnId: "2633",
    seed: 2,
    region: "midwest",
  },
  {
    name: "Kentucky Wildcats",
    shortName: "Kentucky",
    abbreviation: "UK",
    espnId: "96",
    seed: 3,
    region: "midwest",
  },
  {
    name: "Purdue Boilermakers",
    shortName: "Purdue",
    abbreviation: "PUR",
    espnId: "2509",
    seed: 4,
    region: "midwest",
  },
  {
    name: "Clemson Tigers",
    shortName: "Clemson",
    abbreviation: "CLEM",
    espnId: "228",
    seed: 5,
    region: "midwest",
  },
  {
    name: "Illinois Fighting Illini",
    shortName: "Illinois",
    abbreviation: "ILL",
    espnId: "356",
    seed: 6,
    region: "midwest",
  },
  {
    name: "UCLA Bruins",
    shortName: "UCLA",
    abbreviation: "UCLA",
    espnId: "26",
    seed: 7,
    region: "midwest",
  },
  {
    name: "Gonzaga Bulldogs",
    shortName: "Gonzaga",
    abbreviation: "GONZ",
    espnId: "2250",
    seed: 8,
    region: "midwest",
  },
  {
    name: "Georgia Bulldogs",
    shortName: "Georgia",
    abbreviation: "UGA",
    espnId: "61",
    seed: 9,
    region: "midwest",
  },
  {
    name: "Utah State Aggies",
    shortName: "Utah State",
    abbreviation: "USU",
    espnId: "328",
    seed: 10,
    region: "midwest",
  },
  {
    name: "Xavier Musketeers",
    shortName: "Xavier",
    abbreviation: "XAV",
    espnId: "2752",
    seed: 11,
    region: "midwest",
  },
  {
    name: "Texas Longhorns",
    shortName: "Texas",
    abbreviation: "TEX",
    espnId: "251",
    seed: 11,
    region: "midwest",
  },
  {
    name: "McNeese Cowboys",
    shortName: "McNeese",
    abbreviation: "MCN",
    espnId: "2377",
    seed: 12,
    region: "midwest",
  },
  {
    name: "High Point Panthers",
    shortName: "High Point",
    abbreviation: "HPU",
    espnId: "2272",
    seed: 13,
    region: "midwest",
  },
  {
    name: "Troy Trojans",
    shortName: "Troy",
    abbreviation: "TROY",
    espnId: "2653",
    seed: 14,
    region: "midwest",
  },
  {
    name: "Wofford Terriers",
    shortName: "Wofford",
    abbreviation: "WOF",
    espnId: "2747",
    seed: 15,
    region: "midwest",
  },
  {
    name: "SIU Edwardsville Cougars",
    shortName: "SIUE",
    abbreviation: "SIUE",
    espnId: "2565",
    seed: 16,
    region: "midwest",
  },
];
